version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Setup Gradle
          command: echo y | sdkmanager "ndk;21.4.7075529"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Build and test
          command: ./gradlew build test
          #clean build connectedCheck --stacktrace --no-daemon --build-cache
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

















            

            
            
      #./gradlew -p androidlibrary_lib testDebugUnitTest


#version: 2.1



# Define a job to be invoked later in a workflow.

#jobs:
   #build:
    #docker:
      #- image: cimg/android:2023.02
    #steps:
      #- checkout
          
          
      #- run:
          #name: chmod permissions
          #command: chmod +x ./gradlew
          
      #- run:
          #name: Download Dependencies
          #command: ./gradlew androidDependencies
          
      
          
      #- store_artifacts:
          #path: app/build/reports
          #destination: reports
      
  
      #- run:
          #name: Assemble release build
          #command: |
            #./gradlew clean assemble
            
# Invoke jobs via workflows
#workflows:
  #android-workflow: 
    #jobs:
      #- build
