version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yes | sdkmanager "build-tools;30.0.3" >/dev/null
            yes | sdkmanager "platforms;android-30" >/dev/null
            yes | sdkmanager --update >/dev/null
      - run:
          name: Build and Run Unit Tests
          command: |
            ./gradlew -p androidlibrary/androidlibrary_lib testDebugUnitTest


#version: 2.1



# Define a job to be invoked later in a workflow.

#jobs:
   #build:
    #docker:
      #- image: cimg/android:2023.02
    #steps:
      #- checkout
          
          
      #- run:
          #name: chmod permissions
          #command: chmod +x ./gradlew
          
      #- run:
          #name: Download Dependencies
          #command: ./gradlew androidDependencies
          
      
          
      #- store_artifacts:
          #path: app/build/reports
          #destination: reports
      
  
      #- run:
          #name: Assemble release build
          #command: |
            #./gradlew clean assemble
            
# Invoke jobs via workflows
#workflows:
  #android-workflow: 
    #jobs:
      #- build
