version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30
    #working_directory: ~/androidlibrary_lib
    steps:
      - checkout
      - run:
         
          name: chmod permissions
          command: chmod +x ./gradlew
          
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          
      - run:
          command: ls
       
      - run:
          name: build
          command: |
            ./gradlew clean assemble
            
      - run:
          name: Run Tests
          command: |
            ./gradlew test SnapshotBasicDebugAndroidTest
            
    
            
workflows:
  version: 2
  build:
    jobs:
      - build
            

            
            
      #./gradlew -p androidlibrary_lib testDebugUnitTest


#version: 2.1



# Define a job to be invoked later in a workflow.

#jobs:
   #build:
    #docker:
      #- image: cimg/android:2023.02
    #steps:
      #- checkout
          
          
      #- run:
          #name: chmod permissions
          #command: chmod +x ./gradlew
          
      #- run:
          #name: Download Dependencies
          #command: ./gradlew androidDependencies
          
      
          
      #- store_artifacts:
          #path: app/build/reports
          #destination: reports
      
  
      #- run:
          #name: Assemble release build
          #command: |
            #./gradlew clean assemble
            
# Invoke jobs via workflows
#workflows:
  #android-workflow: 
    #jobs:
      #- build
