version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            echo y | sdkmanager "platforms;android-29" "build-tools;29.0.3"
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Set up environment variables
          command: |
            echo 'export ANDROID_HOME=/usr/local/android-sdk' >> $BASH_ENV
            echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools' >> $BASH_ENV
      - run:
          name: Install Android Studio
          command: |
            wget https://dl.google.com/dl/android/studio/ide-zips/4.1.3.0/android-studio-ide-201.7199119-linux.tar.gz
            tar -xzf android-studio-ide-201.7199119-linux.tar.gz
      - run:
          name: Build project
          command: ./gradlew clean assemble --daemon
      - run:
          name: Run unit tests
          command: ./gradlew test

















