version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - run:
          name: Build project
          command: ./gradlew clean assemble
      - run:
          name: Run unit tests
          command: ./gradlew test

      - run:
          name: Deploy 
          command: |
            uses: actions/setup-java@v1
            with:
            java-version: 1.8

      - run:      
          name: Publish package
          command: mvn publish org.android.androidlibrary 1.0-SNAPSHOT -GITHUB_USERNAME=${Roseline_Bassey} -GITHUB_TOKEN=${JAVA_TOKEN} -mavenUrl=https://maven.pkg.github.com/Roseline-Bassey/androidlibrary

workflows:
  build:
    jobs:
      - build

















