version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.02
      
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      
     restore_cache: &restore_cache
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
          
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          
     update_cache: &update_cache
       save_cache:
         paths:
         - ~/.gradle/caches
         - ~/.gradle/wrapper
       key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}    
         
jobs:
  job_run_tests:
    <<: *config_docker
    <<: *config_env
    steps:
      - <<: *update_sdk
      - checkout
      # Docker caching is not available in free plans
      - <<: *cache_docker
      - <<: *restore_cache
      - <<: *fix_permissions
      - <<: *update_dependencies
      - <<: *update_cache
      - run:
          name: Run Tests
          command: ./gradlew testDebug
      - run:
          name: Save test results (html page, see Artifacts)
          command: |
            mkdir -p test-results/html/
            find . -type d -regex ".*/*reports/tests" -exec cp -avr {} test-results/html/ \;
          when: always
      - run:
          name: Save test results (xml results, see Tests)
          command: |
            mkdir -p test-results/xml/
            find . -type f -regex ".*/*test-results/.*xml" -exec cp {} test-results/xml/ \;
          when: always
          
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results



      





