version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:11.0.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - run:
          name: Build project
          command: ./gradlew clean assemble
      - run:
          name: Run unit tests
          command: ./gradlew clean test

 
      - run:  
          name: Authenticate with GitHub Packages
          command: |   
               echo $GITHUB_TOKEN 
               echo $GITHUB_USERNAME
              
      - run:
          name: Deploy library to GitHub Packages 
          command: |
            mvn package
            mvn clean deploy

      
workflows:
  build:
    jobs:
      - build
  
          

















